### PR TITLE
Initial features

### PR DESCRIPTION
**Pull request by bengerman13**
This creates a docker container that reads from s3 logs and writes to elasticsearch, and deploys it to Cloud Foundry.

still to be done:
- some tests would be nice
- I'm not sure where dev and stage should read from/write to
- none of the variables needed have been added to our vars files

### CODE REVIEW

**Comment by siennathesane** [comment]
I think it's okay. Nothing stood out as a problem to me, but I'm not a ruby guy, so 🤷‍♂

**Review by jontours — APPROVED** [review]
Looks good to me.  I saw your note about questions of where to deploy dev and staging to.  Which is kind of confusing, as you seem to be deploying it also to dev and staging CF.  Which I think makes sense.

**Review by siennathesane — APPROVED** [review]
Same as before, not a Ruby guy, but the principle of it looks great.

**Comment by bengerman13** [comment]
I don't think this is done (I want to write some tests to validate the container once it's built), but I'm . going to merge it now for the sake of change sets that fit in people's brains.

**Pull request merged**
