### PR TITLE
Build in ci

### PR DESCRIPTION
**Pull request by bengerman13**
I think this is all that's needed for deployment

note that the tests currently don't run, this is because I haven't figured out how to do docker-in-docker  on concourse. I think the strategy here will ultimately be either to build some other testing methods using CF, or to test using CircleCI

### CODE REVIEW

**Comment by siennathesane** [comment]
What is the impact of not having CI tests?

**Comment by bengerman13** [comment]
we aren't verifying the code that's pushed

**Comment by siennathesane** [comment]
Right, I mean, if we don't test it, and a change comes through, what is the overall system impact if this fails? We just lose ELB logs, yeah?

**Comment by bengerman13** [comment]
We probably wouldn't lose logs, most likely this would end up with either bad data, or logs not getting to elasticsearch (but still existing in S3)

Probable issues from a bad build:
- logstash fails to start 
- logs are read and indexed to elasticsearch without being parsed (i.e., all we get is a `message` field and some logstash-created metadata)
- logs are read and indexed into elasticsearch with bad parsing (i.e. fields have the wrong data type, or the wrong data is in the wrong fields)
- logstash starts, but logs are not read at all

1 and 4 are the easiest to deal with, 1 and 2 seem the most likely to me

**Review by siennathesane — APPROVED** [review]
> logs not getting to elasticsearch (but still existing in S3)

So long as it's not a formal drain, I'm fine with this in the short term.

**Pull request merged**
